### ISSUE TITLE
Need the ability to force a refresh of IP addresses

### ISSUE THREAD

**Issue by benjcallaghan** [distributedlife/get-ip-addresses#2]
Recently I submitted PR #1 to address a need in a product I'm writing. The PR has already been completed and merged back into this repository. I am requesting that a new version is published to the npm registry. There is a known bug (yarnpkg/yarn#1671) that prevents me from using the GitHub repository directly on Windows. Please update the version in npm so I can continue using this package.

**Comment by distributedlife** [comment]
Done. Apologies, I forgot that there was an important second part to all
this.

**Comment by benjcallaghan** [comment]
Thank you. Our product is still in beta, so we have a little more time to take care of it. I would also recommend tagging the source code and making a GitHub release with the same version number. That will make it easier to track versions.
